### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by mrjackv** [simons-public/protonfixes#118]
As the title states the wiki is quite outdated.
Things that need updating:

- Remove `Installation` or reference it in `README.md` (it doesn't make sense to have the same instructions in 2 places or discordant instructions)
- `List of Fixes` hasn't been updated in 2 years
- The `Gamefix utilities` section of `Writing Gamefixes` is a bit outdated, some new commands have been included in `utils` and `download` that might be nice documenting
- There is `wiki/Gamefix-Utilities` which is linked from `README.md` and `wiki/Writing-Gamefixes#gamefix-utilities` which is shown in the main page of the wiki

**Comment by techtonik** [comment]
@mrjackv it is possible to `git clone https://github.com/simons-public/protonfixes.wiki.git` and move its contents into `docs` subdir with a PR.

**Comment by bmaupin** [comment]
> @mrjackv it is possible to `git clone https://github.com/simons-public/protonfixes.wiki.git` and move its contents into `docs` subdir with a PR.

I like the idea of having the wiki content in the repository itself (in a subdirectory or a different branch) so that others can submit PRs for changes. It could help relieve some of the burden of keeping the content updated, which is hard as an open-source maintainer (or just any normal human being who has a life outside of GitHub :smile:)

**Comment by techtonik** [comment]
@bmaupin #166 should do it.
