### ISSUE TITLE
Corefonts and nvapi fixes are not needed anymore

### ISSUE THREAD

**Issue by vanyasem** [simons-public/protonfixes#36]
A new version of Proton (3.16-4 Beta) was released that integrated corefonts and nvapi patches: https://www.gamingonlinux.com/articles/valve-have-pushed-out-another-steam-play-update-with-the-316-4-beta-including-corefonts-support.12875

**Comment by NoXPhasma** [comment]
Don't want to open up a new issue, since it fits in here. There are now some bugs with protonfixes and Proton 3.16-4.

For once, on new prefixes I get this error message sometimes, this gets reported even games don't have any gamefixes.:
```Proton: ************************************************
Proton: THERE IS AN ERROR IN YOUR user_settings.py FILE:
Proton: 'ascii' codec can't decode byte 0xe2 in position 65: ordinal not in range(128)
Proton: ************************************************
```

On other prefixes, no matter if new or old, the Zenity progress window doesn't go away, it stays up in focus. I just tested a few games, but this happens on Batman: Arkham Asylum and 100,000 BC. However, this could be related to the fonts already been installed, which throws this error:
```
Proton: ************************************************
Proton: THERE IS AN ERROR IN YOUR user_settings.py FILE:
Proton: [Errno 17] File exists: '/home/noxp/.config/protonfixes/mscorefonts/arialbi.ttf' -> '/media/daten/SteamApps/steamapps/compatdata/35140/pfx/drive_c/windows/Fonts/arialbi.ttf'
Proton: ************************************************
```
This can be prevented by not installing corefonts if they are already installed. Like
```python
def link_fonts(directory):
    """ Make links to core fonts in directory
    """

    log.info('Creating MS Core font links in ' + directory)
    src = COREFONTS_DIR
    dst = directory
    try:
        [os.symlink(os.path.join(d, f), os.path.join(dst, f))
            for d, _, files in os.walk(src)
            for f in files]
    except:
        print('Corefonts already installed')
```

**Comment by pchome** [comment]
@vanyasem 
... and nvapi patches

No, ` Nvidia cards are now reported as AMD cards`, that's all.

@NoXPhasma 
You can use `~/.config/protonfixes/config.ini` as temporary fix for corefonts and zenity
```ini
[main]
enable_checks = false
enable_splash = false
enable_font_links = false
```

**Comment by NoXPhasma** [comment]
@pchome Thanks.

**Comment by pchome** [comment]
@NoXPhasma 
I'm using several git versions with symlink to currently desired in my `~/.local/lib/python3.6/site-packages/`.

That's easier to use/update (`git pull`).
```
~protonfixes -> protonfixes.git/protonfixes
/protonfixes.git
/protonfixes.my
/protonfixes.orig
```

**Comment by simons-public** [comment]
I added a try/except for symlinking corefonts that should fix the error when the files already exist.

@vanyasem I'm going to keep the corefonts and nvapi fix since there will probably still be people using Proton 3.7 that will need them. 

@NoXPhasma I've uploaded the last commit to pypi so you should be able to update it from pip now. I wasn't able to replicate the `'ascii' codec` error you were getting, would you mind opening another issue with some more details?

**Comment by NoXPhasma** [comment]
Sure.
