### ISSUE TITLE
Support native linux games

### ISSUE THREAD

**Issue by pchome** [simons-public/protonfixes#55]
Not really an "Feature request", but rather a question.

**Describe the solution you'd like**
An possibility to use the same approach for native linux games launched from Steam.

The key feature of `protonfixes` is `winetricks` support, but there is some features may be useful for "regular" games. Like 'env vars', 'command args', 'file installation' and so on.

So, there is actually two questions:
* is it worth ?
  Currently I don't know how to make this work the same way as for Proton, so the obvious way is to set e.g. `steamfixes.py %command%` in Steam's "Launch options" for every game.
* is it possible to hook ?
  Steam using `bash`(`sh`?), `. "${PATH_TO}/custom.sh` somewhere should work, but it's hard for python script to take control on env vars, or command args.

**Describe alternatives you've considered**
Steam's "Launch options", or custom script which replacing real game's executable name, Feral's `config/extra-environment.sh` scripts.

**Additional context**
https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting

**Comment by simons-public** [comment]
It's certainly doable with some modifications on the interactions with proton. I'll do some testing and see if there's a way to load it up without using Launch options as well.

**Comment by pchome** [comment]
I've found an mention about  `$STEAM_DIR/compatibilitytools.d/` in the https://github.com/Sirmentio/protontricks repo's issues.

It's looks like users can register a custom Proton builds (or scripts) in that directory, and I'm wondering is it possible to register an custom script as an "compatibility tool" for linux games. Still I can't find any other info about `compatibilitytools.d/`.

But if it'll work for linux, then it should be like:
* compatibilitytool.vdf -- describing path to the tool
* toolmanifest.vdf -- inside tool's directory, describing command

**Comment by simons-public** [comment]
If you want an example of a working compatibility tool that works (kind of) I have another project called Ion that I've been working on. It only launches games that don't need the steam api at the moment. 

The hard part about using compatibilitytools.d is that it would have to be selected in steamplay settings, which would also disable proton. I'm sure there's another way using LD_PRELOAD and capturing the fork() call that steam uses to launch games, I'll give it a try when I get home today.

**Comment by simons-public** [comment]
Here's a [gist with an example](https://gist.github.com/simons-public/5890e7b5ca7e2375ba24223ce815f23a) of how you can override execve with LD_PRELOAD and load a python script that runs the command instead if the `SteamAppId` environment variable is set. 

I added the Makefile and a test script so you can check it out. I think I'll get a repository going and see what can be done. The only difficult thing would be packaging the `.so` file for easy installation.

**Comment by simons-public** [comment]
I picked ~/.local/share because it's the default DATA_HOME directory for the XDG base directory specification. I've actually been meaning to move protonfixes to the same directory (with some migration code for the old `.config` location).

The `loader.so` should be installed in `/usr/lib/steamfixes/loader.so` just to keep it separate from the rest of the libraries. If you use `make install` that's where it should get installed. I didn't want it to be in any of the library search paths (`ldconfig -v 2>/dev/null | grep ':'` to see) so it wouldn't interfere with any other applications.

I'll probably throw together a PKGBUILD once it's more mature, but putting it in system-wide locations makes it easy to also change the steam command line to `/usr/bin/steamfixes %command%` for a single game. I could probably put in some macros to compile it for different locations later though.
