### ISSUE TITLE
Implement current status on splash screen

### ISSUE THREAD

**Issue by simons-public** [simons-public/protonfixes#8]
Some winetricks take a very long time, cefpython3 can be used to display the current status of protonfixes

**Comment by pchome** [comment]
I'm using the following hack, to display current `winetricks` status (`enable_splash = false`):
```diff
diff --git a/protonfixes/util.py b/protonfixes/util.py
index bf79bd5..9dbb489 100644
--- a/protonfixes/util.py
+++ b/protonfixes/util.py
@@ -154,6 +154,22 @@ def protontricks(verb):
         winetricks_bin = which('winetricks')
         winetricks_cmd = [winetricks_bin, '--unattended'] + verb.split(' ')
 
+        # https://developer.gnome.org/pango/stable/PangoMarkupFormat.html
+        zenity_cmd = [
+                '/usr/bin/zenity',
+                '--progress',
+                '--pulsate',
+                '--no-cancel',
+                '--auto-close',
+                '--width=320',
+                '--text',
+                '<b>ProtonFixes</b> is running the\n\
+<span font_desc="Terminus (TTF) 10" bgcolor="black" foreground="lightgrey">\
+$ winetricks ' + verb + ' \
+</span>\n\
+command, please wait...',
+                ]
+
         # check is verb a custom winetricks verb
         custom_verb = is_custom_verb(verb)
         if custom_verb:
@@ -179,8 +198,10 @@ def protontricks(verb):
 
             log.info('Using winetricks verb ' + verb)
             subprocess.call([env['WINESERVER'], '-w'], env=env)
-            process = subprocess.Popen(winetricks_cmd, env=env)
-            process.wait()
+            wt = subprocess.Popen(winetricks_cmd, env=env, stdout=subprocess.PIPE)
+            zt = subprocess.Popen(zenity_cmd, stdin=wt.stdout)
+            wt.stdout.close()
+            zt.communicate()
             _killhanging()
             log.info('Winetricks complete')
             return True

```

Displays something like:
* -
    <b>ProtonFixes</b> is running the
    `$ winetricks vd=1920x1080`
    command, please wait...

**Comment by mrjackv** [comment]
A bit of a radical proposal...
It would be much better to have some kind of progress bar. Both splash options support it (on cef it can be achieved with some html/css and [Browser.executeFunction](https://github.com/cztomczak/cefpython/blob/master/api/Browser.md#executefunction) ).   It can be achieved by:
* Before loading the fix module, load it in python ast and [count the number](https://suhas.org/function-call-ast-python/)  of "long" function calls (eg. `utils.protontricks`, `utils.use_win32_prefix` or `download.gdrive_download` once it gets merged :wink: ) and build a number of steps, each time the `main()` function calls one of this "long" methods the progress bar is incremented.  
As for deciding the long functions I thought of 2 ways:
* A statically defined list in the module that will be running the ast analysis on the fix and a `splash.increment_progress` function at the end of each function
* (more elegant) using a decorator like `@trackprogress` that combines something like [this](https://stackoverflow.com/questions/5707589/calling-functions-by-array-index-in-python/5707605#5707605) (where the decorator is used to dynamically create a list of functions to track for progress) and to wrap the function so that when it terminates it calls `splash.increment_progress`
